# Generated by Django 5.2.6 on 2025-09-10 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da conversa.', primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a conversa foi criada.')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('usuario', 'Usuário'), ('modelo', 'Modelo')], help_text="O papel de quem enviou a mensagem (ex: 'usuário' ou 'modelo').", max_length=10)),
                ('texto', models.TextField(help_text='O conteúdo da mensagem.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi criada.')),
                ('conversa', models.ForeignKey(help_text='A conversa à qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
