# Generated by Django 5.2.6 on 2025-09-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversa_remove_message_conversation_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversa',
            options={'ordering': ['-modificado_em'], 'verbose_name': 'conversa', 'verbose_name_plural': 'conversas'},
        ),
        migrations.AddField(
            model_name='conversa',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da conversa.'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='titulo',
            field=models.CharField(blank=True, default='Nova Conversa', help_text='Título da conversa para exibição na interface.', max_length=255),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados adicionais em formato JSON.'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='papel',
            field=models.CharField(choices=[('user', 'Usuário'), ('model', 'Modelo')], help_text="O papel de quem enviou a mensagem (ex: 'user' ou 'model').", max_length=10),
        ),
    ]
